#### Label and Ordinal encoding are used to convert categorical data into numerical data

# Label Encoding

#### Label encoding is converting categorical data into a numerical data without any order

#### Red : 2
#### Green : 1
#### Blue : 0

In [1]:
import pandas as pd

df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'blue', 'red', 'red', 'red', 'green']
})

In [2]:
df.head()

   color
0    red
1   blue
2  green
3  green
4   blue

In [3]:
from sklearn.preprocessing import LabelEncoder

# create a instance of LabelEncoder
lbl_encoder = LabelEncoder()

In [4]:
color_encoded = lbl_encoder.fit_transform(df[['color']])

C:\Users\CIT\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [5]:
color_encoded

array([2, 0, 1, 1, 0, 2, 2, 2, 1])

In [6]:
lbl_encoder.transform(['blue'])[0]

np.int64(0)

# Ordinal Encoding

#### Ordinal encoding also converts categorical data into a numerical data but intentionally preserves a meaningful order

#### small : 0
#### mediaum : 1
#### large : 2

In [7]:
df = pd.DataFrame({
    'order' : ['small', 'medium', 'small', 'large', 'medium', 'medium', 'large', 'large'],
})

In [8]:
df.head()

    order
0   small
1  medium
2   small
3   large
4  medium

In [9]:
from sklearn.preprocessing import OrdinalEncoder

# create a instance of OrdinalEncoder
encoder = OrdinalEncoder(categories = [['small', 'medium', 'large']])

In [10]:
encoded = encoder.fit_transform(df[['order']])

In [11]:
encoded

array([[0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.]])

In [13]:
encoder.transform([['small']])

C:\Users\CIT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])