# Target Guided Encoding

#### It's a technique used to encode the categorical variable based on the relationship with the target variable. It's used when we have large of unique categories

#### In Target Guided Encoding we replace the categorical variable with the numerical value based on the mean, median of the target variable for that category. It creates the monotanic relationship between the categorical variable and the target variable which can increase the predictive power of the model.

In [2]:
import pandas as pd

df = pd.DataFrame({
    'city' : ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [3]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [5]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [6]:
mean_price

{'London': 150.0,
 'New York': 190.0,
 'Paris': 300.0,
 'Tokyo': 250.0,
 'paris': 320.0}

In [7]:
df['city_encoded'] = df['city'].map(mean_price)

In [8]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         300.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     paris    320         320.0

In [9]:
import seaborn as sns
dataset = sns.load_dataset('tips')

In [10]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
bill_mean_price = dataset.groupby('time')['total_bill'].mean().to_dict()

C:\Users\CIT\AppData\Local\Temp\ipykernel_18664\158851932.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bill_mean_price = dataset.groupby('time')['total_bill'].mean().to_dict()

In [12]:
bill_mean_price

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [14]:
dataset['time_encoded'] = dataset['time'].map(bill_mean_price)

In [17]:
dataset[dataset['time']=='Lunch']

     total_bill   tip     sex smoker   day   time  size time_encoded
77        27.20  4.00    Male     No  Thur  Lunch     4    17.168676
78        22.76  3.00    Male     No  Thur  Lunch     2    17.168676
79        17.29  2.71    Male     No  Thur  Lunch     2    17.168676
80        19.44  3.00    Male    Yes  Thur  Lunch     2    17.168676
81        16.66  3.40    Male     No  Thur  Lunch     2    17.168676
..          ...   ...     ...    ...   ...    ...   ...          ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1    17.168676
223       15.98  3.00  Female     No   Fri  Lunch     3    17.168676
224       13.42  1.58    Male    Yes   Fri  Lunch     2    17.168676
225       16.27  2.50  Female    Yes   Fri  Lunch     2    17.168676
226       10.09  2.00  Female    Yes   Fri  Lunch     2    17.168676

[68 rows x 8 columns]